language: python

python:
  - "3.5"

sudo: required

services:
  - docker

install: "pip install -r requirements.txt"

env:
  matrix:
    - ANDROID_VERSION=5.0.1 PROCESSOR=x86
    - ANDROID_VERSION=5.0.1 PROCESSOR=arm
    - ANDROID_VERSION=5.1.1 PROCESSOR=x86
    - ANDROID_VERSION=5.1.1 PROCESSOR=arm
    - ANDROID_VERSION=6.0 PROCESSOR=x86
    - ANDROID_VERSION=6.0 PROCESSOR=arm
    - ANDROID_VERSION=7.0 PROCESSOR=x86
    - ANDROID_VERSION=7.0 PROCESSOR=arm
    - ANDROID_VERSION=7.1.1 PROCESSOR=x86
    - ANDROID_VERSION=7.1.1 PROCESSOR=arm
    - ANDROID_VERSION=device PROCESSOR=device

script: bash travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
